### ISSUE TITLE
feature request: function to calculate number of ESS meeting specified condition

### ISSUE THREAD

**Issue by jelber2** [richelbilderbeek/tracerer#7]
For extended Bayesian skyline plots, there can be hundreds even thousands of ESS values. It might be nice to write a function within tracerer (rather than the user cobling together his/her own) that tells you what ESS are not greater or less than a certain value, say "200", which from my understanding is the rule of thumb for acceptable ESS values.

**Comment by jelber2** [comment]
`# Calculates the effective sample sizes of all parameter estimates
esses <- calc_esses(beast_log, sample_interval = 1000)`

`# Calculates the number of effective sample sizes greater than or equal to 200 (a general value for an acceptable effective sample size
length(esses[esses >= 200])`

**Comment by richelbilderbeek** [comment]
May I suggest then not to add an explicit function for this? 

If you agree, click 'Close' :+1:. 

Else I would enjoy adding this Issue to a function's documentation, but I need a minimal and complete example for this. I have no idea how to write this myself, so I will need your help then.
